import numpy as np
import pandas as pd
from pytest import approx
from cdsc.analysis.suppression import estimate_suppression
from cdsc.analysis.threshold import estimate_threshold, fss
from cdsc.sweep.run import wilson_interval


# The Wilson interval matches known values
def test_wilson_interval_matches_known_values():
    assert wilson_interval(10, 100, z=1.96) == approx((0.0552, 0.1744), abs=1e-4)
    # With no errors the upper bound is z^2 / (n + z^2)
    assert wilson_interval(0, 100, z=1.0) == approx((0.0, 1.0 / 101))


# The threshold fit recovers p_th and nu from data generated by its own model
def test_threshold_fit_recovers_the_crossing():
    p_th, nu = 0.007, 1.3
    rows = [
        {"p": p, "d": d, "pl": fss((p, d), p_th, nu, 0.05, 2.0, 10.0), "shots": 10**6}
        for d in (5, 7, 9)
        for p in np.arange(0.005, 0.009 + 1e-9, 0.00025)
    ]
    samples = pd.DataFrame(rows)
    samples["sigma"] = 0.01 * samples["pl"]

    result = estimate_threshold(samples, distances=[5, 7, 9], x_window=0.05, nu_0=1.1)
    assert result.p_th == approx(p_th, rel=1e-6)
    assert result.nu == approx(nu, rel=1e-6)


# The suppression fit recovers the slope and the teraquop distance from exponentially decaying data
def test_suppression_fit_recovers_slope_and_teraquop_distance():
    # Per-round rate eps = 10^(-1 - 0.3 d), turned into a failure rate over d rounds
    slope, intercept, target_pl = -0.3, -1.0, 1e-12
    ds = np.array([3, 5, 7, 9, 11], dtype=float)
    eps = 10 ** (intercept + slope * ds)
    pl = 0.5 * (1 - (1 - 2 * eps) ** ds)
    samples = pd.DataFrame({"d": ds, "pl": pl, "sigma": 0.01 * pl})

    result = estimate_suppression(samples, "rotated_surface", target_pl=target_pl)
    assert result.slope == approx(slope)
    assert result.intercept == approx(intercept)
    # At d_star the per-round rate meets target_pl spread over d_star rounds
    assert 10 ** (intercept + slope * result.d_star) == approx(target_pl / result.d_star, rel=1e-3)
    # The smallest odd distance at or above d_star, and its qubit count 2d^2 - 1
    assert result.d_teraquop == 43
    assert result.qubits == 2 * 43**2 - 1
